Add compilation mode to test scrpit
prenc/saturated_flow_thesis pull request #48
Opened 2020-11-09 12:23 UTC by pectom

2020-11-09 12:42 UTC, prenc requested changes

2020-11-09 12:42 UTC, prenc commented on tests/ModelAnalyzer/TestCaseHandler.py
> +        pcomp = ProgramCompiler(test_params["targets"])
teraz to pc

2020-11-09 12:42 UTC, prenc commented on tests/ModelAnalyzer/TestCaseHandler.py
> +        prun = ProgramRunner(test_params["targets"])
ja bym nazwal p_run

2020-11-15 19:03 UTC, pectom commented on tests/ModelAnalyzer/TestCaseHandler.py
> +        prun = ProgramRunner(test_params["targets"])
dałem pr

2020-11-15 20:45 UTC, prenc approved these changes

2020-11-15 20:45 UTC, merged